depromeet/praise-up-client

.github/ci.yml, .github/git-push.yml, build.sh
> ### 배포 자동화를 위한 ci.yml 파일 추가
---
- Github action 코드를 작성하였습니다.
- `./.github/git-push.yml` , `./build.sh` 추가
- Closes: #2
=> 배포 자동화를 위한 git-push.yml 파일 추가

.github/workflows/git-push.yml
> ### 토큰 인증 방식 변경
---
- 토큰 인증을 remote url 설정시 진행하도록 변경
-  before) `git push` 이후의 계정 인증
- after ) `git remote set-url` 을 통한 토큰 인증 및 remote url 등록
-
=> 토큰 인증 코드 위치 변경

.github/workflows/git-push.yml
> ### 잘못된 git remote command 수정
---
- 잘못된 remote 명령어 수정
=> 잘못된 git remote command 수정

.github/workflows/git-push.yml
> ### remote-url 수정
---
- remote-url에 토큰 삽입 위치를 변경하였습니다.
=> remote-url 수정

src/app/home/index.tsx
> ### 배포 자동화 action 테스트용 PR
---
- 
- home 페이지의 텍스트 css 변경
-
=> 배포 자동화 action 테스트용 PR

.github/workflows/git-push.yml
> ### 팀레포 & 개인 레포 `push` 순서 변경
---
- 팀 레포와 개인 레포의 변경 사항을 모두 merge 한 이후에 양 레포에 push 하도록 변경하였습니다.
- 기존) 팀 레포 `fetch` -> 팀 레포 `merge`&`push` -> 개인 레포 `fetch` -> 개인 레포 `push`
- 변경) 팀 레포&개인 레포 `pull` -> 개인 레포&팀 레포 `push`
-
=> 팀레포 & 개인 레포 push 순서 변경

.github/workflows/git-push.yml
> ### 배포 자동화 action의 remote-url 재수정
---
- 토큰을 포함한 개인 레포 주소를 수정하였습니다.
=> 배포 자동화 action의 remote-url 재수정

.github/workflows/git-push.yml
> ### 배포 자동화 action의 pull branch 설정
---
- 변경사항을 가져올 branch를 지정하지 않아 발생하는 오류를 해결합니다.
- 
-
=> 배포 자동화 action의 pull branch 설정

.github/workflows/git-push.yml
> ### Chaemin-L | fix: 서로 다른 커밋 병합 옵션 추가
---
- 개인 레포의 변경사항 merge 시에 `--allow-unrelated-histories` 옵션을 주어
병합될 수 있도록 하였습니다.
=> 서로 다른 커밋 내역 병합 옵션 추가

.github/workflows/sync_fork.yml
> ### 배포 자동화 파일 이름 변경
---
- 배포 자동화 파일 이름 변경
- 불필요한 팀 레포 fetch 과정 삭제
=> 배포 자동화 파일 이름 변경

.github/workflows/sync_fork.yml
> ### 배포를 위한 개인 레포로만 팀레포 변경사항 반영
---
- 팀 레포로는 두 브랜치를 병합한 커밋을 push 하지 않습니다.
=> 배포를 위한 개인 레포로만 팀레포 변경사항 반영

.github/workflows/sync_fork.yml
> ### 누락된 서로 다른 두 커밋 병합 옵션 추가
---
- 누락된 `--allow-unrelated-histories` 옵션 추가
- #2
=> 누락된 서로 다른 두 커밋 병합 옵션 추가

src/app/home/index.tsx
> ### sync_fork 액션 테스트용 커밋
---
- 액션 테스트용 PR입니다. 
- Home 컴포넌트의 텍스트 변경
- #2
=> sync_fork 액션 테스트용 커밋

.github/workflows/sync_fork.yml
> ### sync_fork 액션내 병합방식 옵션 추가
---
- 두 레포 병합시 발생하는 conflict에는 팀 레포를 따르도록 옵션 추가
- #2
=> sync_fork 액션내 병합방식 옵션 추가

src/app/home/index.tsx
> ### build: sync_fork 액션 테스트용 커밋
---
- 
- 
- #2
=> build: sync_fork 액션 테스트용 커밋

.github/workflows/sync_fork.yml
=> build: update sync_fork.yml

package.json, pnpm-lock.yaml, src/api/index.ts
> ### Axios 기본 세팅
---
- instance 설정
- interceptor 적용
- 에러 핸들링 설정
- axios의 기본 설정 등을 진행하였습니다.
- closes: #27 
- 추후 카카오 로그인 연동을 진행하면서 리프레시 토큰 재발급 로직 및 기타 로직이 추가될 예정입니다.
- `BASE_URL`의 경우, 백엔드 작업이 완료되고 연동 예정입니다.
=> chore: Axios instance 설정 및 interceptor 적용

src/app/home/index.tsx, src/components/layout/default.tsx, src/components/layout/index.tsx
=> feat: add default layout

index.html, src/style/tailwindcss.css, tailwind.config.js
---
- 피그마 디자인과 맞지 않는 corner-smoothing 효과를 임시 제거하였습니다. 
(corner-smoothing을 최소한으로 설정해도 너무 과하게 깎이는 현상)
- `tailwindcss.css`
- `tailwind.config.js`
-
=> style: corner-smoothing 제거

index.html, src/style/tailwindcss.css, tailwind.config.js
---
- smooth-corner 관련 설정 롤백 PR입니다.
- 
-
=> dev to main

src/components/layout/default.tsx, src/components/layout/index.tsx, src/style/global.css
=> fix : modify default layout

src/app/mypage/unregister/unregister-done.tsx
=> jungjjeong | fix: angle props 삭제

src/components/app/archive/marble-detail-card.tsx
=> jungjjeong | fix: 삭제 버튼 이미지 다운로드에서 제외

src/components/app/archive/marble-detail-card.tsx
=> jungjjeong | refactor: 삭제하기 버튼 구조 변경

src/components/app/archive/marble-detail-card.tsx
=> jungjjeong | refactor: backgroundImage 속성 수정

src/api/index.ts, src/components/app/archive/marble-modal.tsx, src/components/app/home/card-swiper.tsx, src/style/swiper/archive-pagination.scss
> ### 게시글이 6개 이상일 경우, 인디케이트가 다이나믹 스타일처럼 변경되도록 수정
---
- 게시글이 6개 이상일 경우, 인디케이트가 다이나믹 스타일처럼 변경되도록 수정
- 공개 예정 게시물, 칭찬 메세지 보기 화면의 스와이퍼를 6개 이상 게시글이 있을 경우에 대하여 수정하였습니다.
- closes: #249
=> feat: 게시글이 6개 이상일 경우, 인디케이트가 다이나믹 스타일처럼 변경되도록 수정

src/app/comment/comment-form.tsx, src/app/post/index.tsx, src/components/app/comment/form-container.tsx, src/components/common/textarea.tsx, src/hooks/useScrollToBottom.ts
> ### 텍스트 영역에 글 입력 시, 동적으로 높이가 늘어나도록
---
- 텍스트 영역에 글 입력 시, 동적으로 높이가 늘어나도록
- `textarea.tsx`
- closes: #252
=> feat: 텍스트 영역에 글 입력 시, 동적으로 높이가 늘어나도록

src/components/common/textarea.tsx
> ### 텍스트 영역에 글 입력 시, 스크롤이 따라오도록 추가
---
- 텍스트 영역에 글 입력 시, 스크롤이 따라오도록 추가
- `textarea.tsx`
- closes: #252
=> feat: 텍스트 영역에 글 입력 시, 스크롤이 따라오도록 추가

src/components/app/archive/marble-card.tsx, src/components/app/detail/menu.tsx
=> jungjjeong | feat: 삭제하기 스트로크 적용

src/hooks/api/my-page/useApiUnregister.tsx
> ### 회원 가입 탈퇴 API URL 수정
---
- 회원 가입 탈퇴 API URL 수정
- 
-
=> fix: 회원 가입 탈퇴 API URL 수정

src/app/archive/marble-canvas.tsx
=> jungjjeong | feat: 화질 개선

src/components/common/button-provider.tsx, src/components/common/fiiled-button.tsx
> ### cta 버튼을 키보드에 반응이 되도록 옵저버 추가
---
- 
- 
-
=> fix: cta 버튼을 키보드에 반응이 되도록 옵저버 추가

package.json, pnpm-lock.yaml, src/components/common/fiiled-button.tsx, vite.config.ts
> ### add Google Analytics
---
- add Google Analytics
- 
-
=> feat: add Google Analytics

vite.config.ts
> ###  modify radar plugin
---
-  modify radar plugin
- 
-
=> fix: modify radar plugin
